### ISSUE TITLE
能否支持 mux

### ISSUE THREAD

**Issue by hexonal** [lotusnetwork/lotusboard#1]

**Comment by lotusnetwork** [comment]
你指的是什么的mux, 我建议你用grpc, grpc很棒

**Comment by hexonal** [comment]
v2ray 中的mux。我也想用grpc。但是有个问题。这样是不是会导致ip快速被封控

**Comment by lotusnetwork** [comment]
怎么会呢
建议看rprx推文, 快加入grpc神教
用grpc可缓解tls in tls

**Comment by hexonal** [comment]
> 怎么会呢
> 
> 建议看rprx推文, 快加入grpc神教
> 
> 用grpc可缓解tls in tls

那请问你这个项目已经支持gprc了吗

**Comment by hexonal** [comment]
看了下,clash pro 是不支持 grpc+ tls 的

**Comment by hexonal** [comment]
我想问下,能否从 v2borad 平滑迁移到你这个项目

**Comment by lotusnetwork** [comment]
可以 但是你不能逆向迁移

**Comment by lotusnetwork** [comment]
> > 怎么会呢
> > 建议看rprx推文, 快加入grpc神教
> > 用grpc可缓解tls in tls
> 
> 那请问你这个项目已经支持gprc了吗

支持了啊 v2b原生支持

**Comment by lotusnetwork** [comment]
我们还支持vless了呢

**Comment by hexonal** [comment]
我是否可以理解为,我可以从 v2board平滑迁移到该项目,且不需要新增表或者改其他的.但是我不能从该项目平滑迁移到 v2borad 呢

**Comment by lotusnetwork** [comment]
是的, 如果你用了vless的话你迁移回v2b你的vless会失效, 但数据库什么的不会炸, 还有我们修复的hysteria的部分bug也会变成v2b还没修的时候的样子

**Comment by hexonal** [comment]
我是直接pull项目进行迁移吗？还是说有推荐的版本，另外想请问一下是否支持套cf的行为呢

**Comment by lotusnetwork** [comment]
能不能看一下wiki

https://lotusnetwork.github.io/zhs/docs/lotusboard_setup.html

**Comment by lotusnetwork** [comment]
支持 你自己前置个caddy或者直接改docker compose用内置的caddy都可以 内置的caddy挺新的 你随便玩都可以

**Comment by lotusnetwork** [comment]
你想办法备份然后数据倒进去我觉得就可以了

**Comment by lotusnetwork** [comment]
或者你直接配置它用remote database

**Comment by hexonal** [comment]
> 能不能看一下wiki
> 
> 
> 
> https://lotusnetwork.github.io/zhs/docs/lotusboard_setup.html

感谢，其实我之前用过和看过，当时你的项目突然迁移到这里了，所以换成了v2board，这次粗略的看了下，但是不确定是否和v2在数据库层面有冲突，实在抱歉

**Comment by lotusnetwork** [comment]
这么说吧 数据库这块是一点都没动....
