### ISSUE TITLE
webserver down

### ISSUE THREAD

**Issue by SPAK007** [lotusnetwork/lotusboard#12]
how to start panel with domain??

should i modify something ??

    volumes:
      - './lotusboard:/www'

???

**Comment by lotusnetwork** [comment]
modify caddy.conf under lotusboard-docker.
replace
```
:80 {
```
with 
```
https://yourdomain.org {
```

and then map port 443 from container to host, thus users can gain access to your site with https
ps: You don't need to manage the certificates manually, caddy will take care of that

**Comment by SPAK007** [comment]
thanks bro. i tried to install panel using aapanel. more stable. less issues.
thanks for your great effort. peace
