### ISSUE TITLE
[bugfix] 当前stash并不支持xtls-rprx-vision-udp443

### ISSUE THREAD

**Issue by hexonal** [lotusnetwork/lotusboard#2]
[vless](https://stash.wiki/proxy-protocols/proxy-types#vless)
可以看到当前只支持：
- xtls-rprx-origin
- xtls-rprx-direct
- xtls-rprx-splice
这三种模式，所以是有问题的

**Comment by hexonal** [comment]
xtls-rprx-vision-udp443 同时会导致小火箭也无法使用

**Comment by lotusnetwork** [comment]
好好好对对对 马上改

**Comment by lotusnetwork** [comment]
改掉了
