### ISSUE TITLE
[bugfix] 当前stash并不支持xtls-rprx-vision

### ISSUE THREAD

**Issue by hexonal** [lotusnetwork/lotusboard#3]

**Comment by lotusnetwork** [comment]
hm 改天修一下

**Comment by lotusnetwork** [comment]
没办法 我们开vless flow其实只有vision这个选项 要不然不开 要不然开vision....因为后端不可能说给你自适应吧

**Comment by hexonal** [comment]
可以理解；我是cr你的代码之后发现还是存在问题的

**Comment by hexonal** [comment]
我使用了小火箭和stash，clashx pro 和clash meta。我发现，对于手机上来说，确实xtls是无法使用的。

**Comment by hexonal** [comment]
不知道您这边是什么配置的方式。如果可以的话，可以贴一下您的配置吗？ 我必须把xtls关闭后才能使用呢

**Comment by lotusnetwork** [comment]
那个xtls是歧义 实际上新版本里那个是vless flow, 后端不需要开启xtls的

**Comment by lotusnetwork** [comment]
为了保持向下兼容性才给它

**Comment by hexonal** [comment]
我不清楚你这里指代的新版是当前我正在使用的版本；还是有段的xray版本。这里的后端指代的是docker镜像的：ghcr.io/xrayr-project/xrayr；如果这个不是新版，那我想知道是不是v2bx是不是您指代的新版本呢？

**Comment by lotusnetwork** [comment]
你看xrayr对应的xray版本 最新的xray版本才能用vless flow 我不知道xrayr有没有跟进到这个版本

**Comment by hexonal** [comment]
[v2bx](https://github.com/InazumaV/V2bX) 我想知道最新的xray是指dev分支还是已经到了master发布分支了呢？能给一个网址吗？

**Comment by hexonal** [comment]
Fix
VLESS 默认启用xtls-rprx-vision流控，xtls-rprx-direct已不再支持，如果启用VLESS，请确保客户端、服务端关闭XTLS。如果希望使用不支持xtls-rprx-vision 的客户端 ，请在客户端修改流控为空 (none)，同时使用TLS。Trojan协议和其XTLS设置仍保持不变，无需更改。
我觉得可以直接兼容到最新版。不需要向下兼容了。这个版本对于xray的xtls变动挺大的。况且你的版本也是一个新版，引入一个向下兼容的功能反而我觉得很鸡肋呀

**Comment by lotusnetwork** [comment]
xray那条消息：当然是stable release

关于xtls： 这里的向下兼容指的不是向下兼容xtls 而是xtls这个switcher实际上打开的是vless flow的分发开关
