### ISSUE TITLE
question on installation and update

### ISSUE THREAD

**Issue by mrkarami1** [lotusnetwork/lotusboard#5]
Hello
this is a great enhancement of v2board.
there are some questions:
if the user uses v2board guide to install the panel, do we need to check availability of mysql in init.sh?
this panel docks to xrayr under the name of Newv2board?
i could not find update.sh in project, does update.sh update panel directly from this repo?
will you continue to maintain this project?

**Comment by lotusnetwork** [comment]
do we need to check availability of mysql in init.sh?: The answer is no, we do not need to check, but you'll need to setup the database and make sure it's working 

Yes, use newv2board

We'll continue to maintain this project 

If you install this program without docker, you'll need to pull from the remote and restart the horizon
