### ISSUE TITLE
重置密码邮件提示 Request failed

### ISSUE THREAD

**Issue by fearlessshi** [lotusnetwork/lotusboard#6]
php 8.0
新装lotusboard 两次，stmp测试都不能发送重置密码邮件，发送测试邮件正常。
相同条件下安装v2board重置密码邮件正常。

**Comment by lotusnetwork** [comment]
数据库里v2_log最近一条去掉敏感信息之后发在这里

**Comment by lotusnetwork** [comment]
> php 8.0 新装lotusboard 两次，stmp测试都不能发送重置密码邮件，发送测试邮件正常。 相同条件下安装v2board重置密码邮件正常。

Fixed at
https://github.com/lotusnetwork/lotusboard/commit/d3c078d8db91d0ab7e6150569f4e3ba5bbc5172c
