### ISSUE TITLE
队列任务工作异常，且执行dc restart无作用

### ISSUE THREAD

**Issue by narwhrl** [lotusnetwork/lotusboard#8]
按文档提示，在容器内执行`dc restart`得到以下输出：
```
bash-5.1# dc restart
dc: can't open 'restart': No such file or directory
```

**Comment by lotusnetwork** [comment]
dc是docker compose 你那个dc应该是一个计算器而不是docker compose

**Comment by narwhrl** [comment]
> dc是docker compose 你那个dc应该是一个计算器而不是docker compose

噢噢感谢，不过文档里最好还是写完整命令比较好😂
